

run:
  timeout: 5m
  allow-parallel-runners: true

output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  depguard:
    rules:
      Main:
        list-mode: lax
        files:
          - $all
          - '!**/internal/**'
        allow:
          - $gostd
          - github.com/iruldev/golang-api-hexagonal
          - github.com/go-chi
          - github.com/google/uuid
          - github.com/jackc/pgx
          - github.com/kelseyhightower/envconfig
          - github.com/go-playground/validator
          - github.com/golang-jwt/jwt
          - github.com/pressly/goose
          - go.opentelemetry.io
          - github.com/prometheus
          - github.com/stretchr/testify
      app-layer:
        list-mode: strict
        files:
          - 'internal/app/**'
          - '!internal/app/**/*_test.go'
        allow:
          - $gostd
          - github.com/iruldev/golang-api-hexagonal/internal/domain
        deny:
          - pkg: log/slog
            desc: App layer must not log directly
          - pkg: go.opentelemetry.io
            desc: App layer must not trace directly
          - pkg: github.com/google/uuid
            desc: App layer must not import UUID library directly
          - pkg: net/http
            desc: App layer must not import HTTP packages
          - pkg: github.com/jackc/pgx/v5
            desc: App layer must not import database drivers
          - pkg: github.com/iruldev/golang-api-hexagonal/internal/transport
            desc: App layer must not import transport layer
          - pkg: github.com/iruldev/golang-api-hexagonal/internal/infra
            desc: App layer must not import infra layer
      app-layer-test:
        list-mode: strict
        files:
          - 'internal/app/**/*_test.go'
        allow:
          - $gostd
          - github.com/iruldev/golang-api-hexagonal/internal/domain
          - github.com/stretchr/testify
        deny:
          - pkg: log/slog
            desc: App tests must not log directly
          - pkg: go.opentelemetry.io
            desc: App tests must not trace directly
          - pkg: github.com/google/uuid
            desc: App tests must not import UUID library directly
          - pkg: net/http
            desc: App tests must not import HTTP packages
          - pkg: github.com/jackc/pgx/v5
            desc: App tests must not import database drivers
          - pkg: github.com/iruldev/golang-api-hexagonal/internal/transport
            desc: App tests must not import transport layer
          - pkg: github.com/iruldev/golang-api-hexagonal/internal/infra
            desc: App tests must not import infra layer
      domain-layer:
        list-mode: strict
        files:
          - 'internal/domain/**'
          - '!internal/domain/**/*_test.go'
        allow:
          - $gostd
        deny:
          - pkg: log/slog
            desc: Domain layer must not log
      domain-layer-test:
        list-mode: strict
        files:
          - 'internal/domain/**/*_test.go'
        allow:
          - $gostd
          - github.com/stretchr/testify
        deny:
          - pkg: log/slog
            desc: Domain tests must not log
      infra-layer:
        list-mode: strict
        files:
          - '**/internal/infra/**'
          - '!**/internal/infra/**/*_test.go'
          - '!**/internal/infra/fx/**'
        allow:
          - $gostd
          - github.com/iruldev/golang-api-hexagonal/internal/domain
          - github.com/iruldev/golang-api-hexagonal/internal/shared
          - github.com/iruldev/golang-api-hexagonal/internal/infra
          - github.com/iruldev/golang-api-hexagonal/internal/transport/http/ctxutil
          - github.com/jackc/pgx/v5
          - github.com/pressly/goose/v3
          - go.opentelemetry.io/otel
          - github.com/kelseyhightower/envconfig
          - github.com/google/uuid
          - github.com/prometheus/client_model/go
          - github.com/prometheus/client_golang/prometheus
          - github.com/prometheus/client_golang/prometheus/collectors
          - github.com/prometheus/client_golang/prometheus/collectors
      wiring-layer:
        list-mode: strict
        files:
          - '**/internal/infra/fx/**'
        allow:
          - $gostd
          - github.com/iruldev/golang-api-hexagonal/internal/app
          - github.com/iruldev/golang-api-hexagonal/internal/domain
          - github.com/iruldev/golang-api-hexagonal/internal/infra
          - github.com/iruldev/golang-api-hexagonal/internal/shared
          - github.com/iruldev/golang-api-hexagonal/internal/transport
          - github.com/go-chi/chi/v5
          - github.com/prometheus/client_golang/prometheus
          - go.opentelemetry.io/otel
          - go.uber.org/fx
          - github.com/stretchr/testify
      transport-layer-test:
        list-mode: lax
        files:
          - '**/internal/transport/**/*_test.go'
        deny:
          - pkg: github.com/jackc/pgx/v5
            desc: Transport layer must not import database drivers
          - pkg: github.com/iruldev/golang-api-hexagonal/internal/infra
            desc: Transport layer must not import infra directly (tests)
      transport-layer:
        list-mode: strict
        files:
          - '**/internal/transport/**'
          - '!**/internal/transport/**/*_test.go'
        allow:
          - $gostd
          - github.com/iruldev/golang-api-hexagonal/internal/app
          - github.com/iruldev/golang-api-hexagonal/internal/domain
          - github.com/iruldev/golang-api-hexagonal/internal/shared
          - github.com/iruldev/golang-api-hexagonal/internal/transport
          - github.com/go-chi/chi/v5
          - github.com/golang-jwt/jwt/v5
          - github.com/go-playground/validator/v10
          - github.com/prometheus/client_golang/prometheus
          - github.com/google/uuid
          - github.com/go-chi/httprate
          - go.opentelemetry.io/otel
          - go.opentelemetry.io/otel/attribute
          - go.opentelemetry.io/otel/propagation
          - go.opentelemetry.io/otel/trace
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - (*encoding/json.Encoder).Encode
      - (io.Writer).Write
      - (net/http.ResponseWriter).Write
      - io.WriteString
      - (*go.opentelemetry.io/otel/sdk/trace.TracerProvider).Shutdown
  staticcheck:
    checks:
      - all
      - '-QF*'  # Disable quickfix suggestions

linters:
  disable-all: true
  enable:
    - depguard
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports

issues:
  exclude-dirs:
    - third_party
    - builtin
    - examples
  exclude-rules:
    # Exclude deprecated API warnings for specific patterns
    - linters:
        - staticcheck
      text: "SA1019.*CloseNotifier"
    - linters:
        - staticcheck
      text: "SA1019.*NewNoopTracerProvider"


