package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	"github.com/google/uuid"
	"github.com/iruldev/golang-api-hexagonal/internal/domain"
	"github.com/iruldev/golang-api-hexagonal/internal/domain/note"
	"github.com/iruldev/golang-api-hexagonal/internal/interface/graphql/model"
)

// CreateNote is the resolver for the createNote field.
func (r *mutationResolver) CreateNote(ctx context.Context, input model.CreateNoteInput) (*note.Note, error) {
	n, err := r.NoteUsecase.Create(ctx, input.Title, input.Content)
	if err != nil {
		return nil, MapError(ctx, err)
	}
	return n, nil
}

// UpdateNote is the resolver for the updateNote field.
func (r *mutationResolver) UpdateNote(ctx context.Context, id string, input model.UpdateNoteInput) (*note.Note, error) {
	noteID, err := uuid.Parse(id)
	if err != nil {
		return nil, MapError(ctx, domain.ErrValidation)
	}
	n, err := r.NoteUsecase.Update(ctx, noteID, input.Title, input.Content)
	if err != nil {
		return nil, MapError(ctx, err)
	}
	return n, nil
}

// DeleteNote is the resolver for the deleteNote field.
func (r *mutationResolver) DeleteNote(ctx context.Context, id string) (bool, error) {
	noteID, err := uuid.Parse(id)
	if err != nil {
		return false, MapError(ctx, domain.ErrValidation)
	}
	err = r.NoteUsecase.Delete(ctx, noteID)
	if err != nil {
		return false, MapError(ctx, err)
	}
	return true, nil
}

// ID is the resolver for the id field.
func (r *noteResolver) ID(ctx context.Context, obj *note.Note) (string, error) {
	return obj.ID.String(), nil
}

// Notes is the resolver for the notes field.
func (r *queryResolver) Notes(ctx context.Context) ([]*note.Note, error) {
	// Default pagination
	notes, _, err := r.NoteUsecase.List(ctx, 1, 100)
	if err != nil {
		return nil, MapError(ctx, err)
	}
	return notes, nil
}

// Note is the resolver for the note field.
func (r *queryResolver) Note(ctx context.Context, id string) (*note.Note, error) {
	noteID, err := uuid.Parse(id)
	if err != nil {
		return nil, MapError(ctx, domain.ErrValidation)
	}
	n, err := r.NoteUsecase.Get(ctx, noteID)
	if err != nil {
		return nil, MapError(ctx, err)
	}
	return n, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Note returns NoteResolver implementation.
func (r *Resolver) Note() NoteResolver { return &noteResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type noteResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
