// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package users

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// CreateUser inserts a new user and returns it
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// DeleteUser removes a user by ID
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	// GetUser retrieves a user by ID
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	// GetUserByEmail retrieves a user by email address
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// ListUsers retrieves all users ordered by creation date
	ListUsers(ctx context.Context) ([]User, error)
	// UpdateUser updates a user's name and returns the updated user
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
