// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: note.sql

package note

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (user_id, title, content)
VALUES ($1, $2, $3)
RETURNING id, user_id, title, content, created_at, updated_at
`

type CreateNoteParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Title   string      `json:"title"`
	Content pgtype.Text `json:"content"`
}

// CreateNote inserts a new note and returns it
func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote, arg.UserID, arg.Title, arg.Content)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes WHERE id = $1
`

// DeleteNote removes a note by ID
func (q *Queries) DeleteNote(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNote, id)
	return err
}

const getNote = `-- name: GetNote :one
SELECT id, user_id, title, content, created_at, updated_at FROM notes WHERE id = $1
`

// GetNote retrieves a note by ID
func (q *Queries) GetNote(ctx context.Context, id pgtype.UUID) (Note, error) {
	row := q.db.QueryRow(ctx, getNote, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotesByUser = `-- name: ListNotesByUser :many
SELECT id, user_id, title, content, created_at, updated_at FROM notes WHERE user_id = $1 ORDER BY created_at DESC
`

// ListNotesByUser retrieves all notes for a user
func (q *Queries) ListNotesByUser(ctx context.Context, userID pgtype.UUID) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET title = $2, content = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, title, content, created_at, updated_at
`

type UpdateNoteParams struct {
	ID      pgtype.UUID `json:"id"`
	Title   string      `json:"title"`
	Content pgtype.Text `json:"content"`
}

// UpdateNote updates a note's title and content
func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNote, arg.ID, arg.Title, arg.Content)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
