// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package note

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// CreateNote inserts a new note and returns it
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	// DeleteNote removes a note by ID
	DeleteNote(ctx context.Context, id pgtype.UUID) error
	// GetNote retrieves a note by ID
	GetNote(ctx context.Context, id pgtype.UUID) (Note, error)
	// ListNotesByUser retrieves all notes for a user
	ListNotesByUser(ctx context.Context, userID pgtype.UUID) ([]Note, error)
	// UpdateNote updates a note's title and content
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error)
}

var _ Querier = (*Queries)(nil)
