// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateNoteInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateNoteInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}
