// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: audit.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditEventsByEntity = `-- name: CountAuditEventsByEntity :one
SELECT COUNT(*) FROM audit_events
WHERE entity_type = $1 AND entity_id = $2
`

type CountAuditEventsByEntityParams struct {
	EntityType string      `db:"entity_type" json:"entity_type"`
	EntityID   pgtype.UUID `db:"entity_id" json:"entity_id"`
}

func (q *Queries) CountAuditEventsByEntity(ctx context.Context, arg CountAuditEventsByEntityParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEventsByEntity, arg.EntityType, arg.EntityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditEvent = `-- name: CreateAuditEvent :exec

INSERT INTO audit_events (id, event_type, actor_id, entity_type, entity_id, payload, timestamp, request_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateAuditEventParams struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	EventType  string             `db:"event_type" json:"event_type"`
	ActorID    pgtype.UUID        `db:"actor_id" json:"actor_id"`
	EntityType string             `db:"entity_type" json:"entity_type"`
	EntityID   pgtype.UUID        `db:"entity_id" json:"entity_id"`
	Payload    []byte             `db:"payload" json:"payload"`
	Timestamp  pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
	RequestID  pgtype.Text        `db:"request_id" json:"request_id"`
}

// Audit queries for sqlc
// Story 5.4: Type-safe SQL queries for Audit module
func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.Exec(ctx, createAuditEvent,
		arg.ID,
		arg.EventType,
		arg.ActorID,
		arg.EntityType,
		arg.EntityID,
		arg.Payload,
		arg.Timestamp,
		arg.RequestID,
	)
	return err
}

const getAuditEventByID = `-- name: GetAuditEventByID :one
SELECT id, event_type, actor_id, entity_type, entity_id, payload, timestamp, request_id
FROM audit_events WHERE id = $1
`

func (q *Queries) GetAuditEventByID(ctx context.Context, id pgtype.UUID) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, getAuditEventByID, id)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.ActorID,
		&i.EntityType,
		&i.EntityID,
		&i.Payload,
		&i.Timestamp,
		&i.RequestID,
	)
	return i, err
}

const listAuditEventsByEntity = `-- name: ListAuditEventsByEntity :many
SELECT id, event_type, actor_id, entity_type, entity_id, payload, timestamp, request_id
FROM audit_events
WHERE entity_type = $1 AND entity_id = $2
ORDER BY timestamp DESC, id DESC
LIMIT $3 OFFSET $4
`

type ListAuditEventsByEntityParams struct {
	EntityType string      `db:"entity_type" json:"entity_type"`
	EntityID   pgtype.UUID `db:"entity_id" json:"entity_id"`
	Limit      int32       `db:"limit" json:"limit"`
	Offset     int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListAuditEventsByEntity(ctx context.Context, arg ListAuditEventsByEntityParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByEntity,
		arg.EntityType,
		arg.EntityID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.ActorID,
			&i.EntityType,
			&i.EntityID,
			&i.Payload,
			&i.Timestamp,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsByRequestID = `-- name: ListAuditEventsByRequestID :many
SELECT id, event_type, actor_id, entity_type, entity_id, payload, timestamp, request_id
FROM audit_events
WHERE request_id = $1
ORDER BY timestamp DESC
`

func (q *Queries) ListAuditEventsByRequestID(ctx context.Context, requestID pgtype.Text) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByRequestID, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.ActorID,
			&i.EntityType,
			&i.EntityID,
			&i.Payload,
			&i.Timestamp,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
