// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: idempotency.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :exec
INSERT INTO idempotency_keys (key, request_hash, status_code, response_headers, response_body, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateIdempotencyKeyParams struct {
	Key             string             `db:"key" json:"key"`
	RequestHash     string             `db:"request_hash" json:"request_hash"`
	StatusCode      int32              `db:"status_code" json:"status_code"`
	ResponseHeaders []byte             `db:"response_headers" json:"response_headers"`
	ResponseBody    []byte             `db:"response_body" json:"response_body"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

// Stores a new idempotency key record
func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, createIdempotencyKey,
		arg.Key,
		arg.RequestHash,
		arg.StatusCode,
		arg.ResponseHeaders,
		arg.ResponseBody,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE expires_at <= NOW()
`

// Removes all expired idempotency key records and returns the count of deleted rows
func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one

SELECT key, request_hash, status_code, response_headers, response_body, created_at, expires_at
FROM idempotency_keys
WHERE key = $1 AND expires_at > NOW()
`

// Idempotency key queries for sqlc
// Story 2.5: Idempotency Storage Implementation
// Retrieves an idempotency key record if it exists and hasn't expired
func (q *Queries) GetIdempotencyKey(ctx context.Context, key string) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.RequestHash,
		&i.StatusCode,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
