// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	EventType  string             `db:"event_type" json:"event_type"`
	ActorID    pgtype.UUID        `db:"actor_id" json:"actor_id"`
	EntityType string             `db:"entity_type" json:"entity_type"`
	EntityID   pgtype.UUID        `db:"entity_id" json:"entity_id"`
	Payload    []byte             `db:"payload" json:"payload"`
	Timestamp  pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
	RequestID  pgtype.Text        `db:"request_id" json:"request_id"`
}

type SchemaInfo struct {
	ID            int32              `db:"id" json:"id"`
	Version       string             `db:"version" json:"version"`
	Description   pgtype.Text        `db:"description" json:"description"`
	InitializedAt pgtype.Timestamptz `db:"initialized_at" json:"initialized_at"`
}

type User struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Email     string             `db:"email" json:"email"`
	FirstName string             `db:"first_name" json:"first_name"`
	LastName  string             `db:"last_name" json:"last_name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
