// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/iruldev/golang-api-hexagonal/internal/domain (interfaces: AuditEventRepository)
//
// Generated by this command:
//
//	mockgen -destination=../testutil/mocks/audit_event_repository_mock.go -package=mocks github.com/iruldev/golang-api-hexagonal/internal/domain AuditEventRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/iruldev/golang-api-hexagonal/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditEventRepository is a mock of AuditEventRepository interface.
type MockAuditEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuditEventRepositoryMockRecorder
	isgomock struct{}
}

// MockAuditEventRepositoryMockRecorder is the mock recorder for MockAuditEventRepository.
type MockAuditEventRepositoryMockRecorder struct {
	mock *MockAuditEventRepository
}

// NewMockAuditEventRepository creates a new mock instance.
func NewMockAuditEventRepository(ctrl *gomock.Controller) *MockAuditEventRepository {
	mock := &MockAuditEventRepository{ctrl: ctrl}
	mock.recorder = &MockAuditEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditEventRepository) EXPECT() *MockAuditEventRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuditEventRepository) Create(ctx context.Context, q domain.Querier, event *domain.AuditEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, q, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAuditEventRepositoryMockRecorder) Create(ctx, q, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuditEventRepository)(nil).Create), ctx, q, event)
}

// ListByEntityID mocks base method.
func (m *MockAuditEventRepository) ListByEntityID(ctx context.Context, q domain.Querier, entityType string, entityID domain.ID, params domain.ListParams) ([]domain.AuditEvent, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByEntityID", ctx, q, entityType, entityID, params)
	ret0, _ := ret[0].([]domain.AuditEvent)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByEntityID indicates an expected call of ListByEntityID.
func (mr *MockAuditEventRepositoryMockRecorder) ListByEntityID(ctx, q, entityType, entityID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByEntityID", reflect.TypeOf((*MockAuditEventRepository)(nil).ListByEntityID), ctx, q, entityType, entityID, params)
}
