// Package mocks contains generated mock implementations for testing.
//
// This package is the centralized location for all generated mocks.
// Mocks are generated using uber-go/mock (mockgen) and should NOT
// be edited manually.
//
// Mock generation is triggered via:
//   - make mocks: regenerate all mocks
//   - go generate ./...: generate from //go:generate directives
//
// Convention:
//   - Mock files are named: {interface}_mock.go
//   - All mocks contain "Code generated by MockGen" marker
//   - Mocks are generated from port interfaces (internal/{domain}/port/)
//
// Story 1.2 will implement mock generation setup.
package mocks
